baseURL = "http://hmleal.github.io"
languageCode = "en-us"
title = "hmleal"
theme = "hmleal-theme"

sectionPagesMenu = "main"

googleAnalytics = "UA-58687169-1"

[params]
  description = "Another dev blog written in Hugo"
